services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: student
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - data_mysql:/var/lib/mysql
    networks:
      - my-network

  app:
    image: louay222/fy:9.0.0  # Remplacez par le nom de votre image Spring Boot
    depends_on:
      - db
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://db:3306/student?createDatabaseIfNotExist=true",
        "spring.datasource.username": "admin",
        "spring.datasource.password": "root",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    networks:
      - my-network



  prometheus:
    image: bitnami/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /home/ubuntu/devops/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stoppe
 

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    networks:
      - my-network
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin  # Correction de la syntaxe

networks:
  my-network:
    driver: bridge

volumes:
  data_mysql:
  prometheus-data:  # Volume pour les données de Prometheus
